vk-groups:
  - dobrye_ryki_izh
  - otdam_zoo_izevsk
  - zoopoisk_18
  - zhivotnye_izhevska
  - houseizhevsk
  - im_nuzhen_dom18
  - club199572952
  - club115762840
  - kyterg_izhevsk
  - animal18
  - teremok_izhevsk
  - club72714266
  - club133962148
  - pethelpudm
  - o_udm
  - poteryashka_18
  - kot_i_pec
  - volshebnyepsy
