-- name: UpsertPost :exec
-- Insert or update a post with all parsed fields
INSERT INTO posts (
  owner_id,
  post_id,
  date,
  text,
  raw,
  type,
  animal,
  breed,
  sex,
  age,
  name,
  location,
  "when",
  phones,
  contact_names,
  vk_accounts,
  status_details,
  extras_sterilized,
  extras_vaccinated,
  extras_chipped,
  extras_litter_ok
)
VALUES (
  @owner_id,
  @post_id,
  @date,
  @text,
  @raw,
  @type,
  @animal,
  @breed,
  @sex,
  @age,
  @name,
  @location,
  @when,
  @phones,
  @contact_names,
  @vk_accounts,
  @status_details,
  @extras_sterilized,
  @extras_vaccinated,
  @extras_chipped,
  @extras_litter_ok
)
ON CONFLICT(owner_id, post_id) DO UPDATE SET
  date = excluded.date,
  text = excluded.text,
  raw = excluded.raw,
  type = excluded.type,
  animal = excluded.animal,
  breed = excluded.breed,
  sex = excluded.sex,
  age = excluded.age,
  name = excluded.name,
  location = excluded.location,
  "when" = excluded."when",
  phones = excluded.phones,
  contact_names = excluded.contact_names,
  vk_accounts = excluded.vk_accounts,
  status_details = excluded.status_details,
  extras_sterilized = excluded.extras_sterilized,
  extras_vaccinated = excluded.extras_vaccinated,
  extras_chipped = excluded.extras_chipped,
  extras_litter_ok = excluded.extras_litter_ok;
