services:
  lostdogs:
    image: ${IMAGE:-jehaby/lostdogs:latest}
    container_name: ${CONTAINER_NAME:-lostdogs}
    restart: unless-stopped
    working_dir: /app
    entrypoint: [ "/app/lostdogs" ]
    env_file:
      - path: .env
        required: true
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ${DB_VOLUME_NAME:-lostdogs_db_data}:${DB_DIR_IN_CONTAINER:-/data}

volumes:
  lostdogs_db_data: {}
