// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Post struct {
	OwnerID          int64     `json:"owner_id"`
	PostID           int64     `json:"post_id"`
	Date             int64     `json:"date"`
	Text             string    `json:"text"`
	Raw              string    `json:"raw"`
	Type             *string   `json:"type"`
	Animal           *string   `json:"animal"`
	Breed            *string   `json:"breed"`
	Sex              *string   `json:"sex"`
	Age              *string   `json:"age"`
	Name             *string   `json:"name"`
	Location         *string   `json:"location"`
	When             *string   `json:"when"`
	Phones           *string   `json:"phones"`
	ContactNames     *string   `json:"contact_names"`
	VkAccounts       *string   `json:"vk_accounts"`
	StatusDetails    *string   `json:"status_details"`
	ExtrasSterilized *int64    `json:"extras_sterilized"`
	ExtrasVaccinated *int64    `json:"extras_vaccinated"`
	ExtrasChipped    *int64    `json:"extras_chipped"`
	ExtrasLitterOk   *int64    `json:"extras_litter_ok"`
	CreatedAt        time.Time `json:"created_at"`
}
