// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jehaby/lostdogs/internal/types"
)

type Outbox struct {
	ID          int64     `json:"id"`
	OwnerID     int64     `json:"owner_id"`
	PostID      int64     `json:"post_id"`
	Status      string    `json:"status"`
	Retries     int64     `json:"retries"`
	LastError   *string   `json:"last_error"`
	TgMessageID *int64    `json:"tg_message_id"`
	LeasedUntil *int64    `json:"leased_until"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Post struct {
	OwnerID       int64             `json:"owner_id"`
	PostID        int64             `json:"post_id"`
	Date          int64             `json:"date"`
	Text          string            `json:"text"`
	Raw           string            `json:"raw"`
	Type          string            `json:"type"`
	Animal        string            `json:"animal"`
	Sex           string            `json:"sex"`
	Name          *string           `json:"name"`
	Location      *string           `json:"location"`
	When          *string           `json:"when"`
	Phones        types.StringSlice `json:"phones"`
	ContactNames  types.StringSlice `json:"contact_names"`
	VkAccounts    types.StringSlice `json:"vk_accounts"`
	Photos        types.StringSlice `json:"photos"`
	StatusDetails *string           `json:"status_details"`
	CreatedAt     time.Time         `json:"created_at"`
}
